const SECOND_MS = 1000;
const MINUTE_MS = 60 * SECOND_MS;
const DAY_MS = 24 * 60 * MINUTE_MS;

export const STOCK_PRICE_CACHE_TTL_MS = 30 * MINUTE_MS;
export const STOCK_PRICE_REFRESH_COOLDOWN_MS = 15 * SECOND_MS;
export const ETF_HOLDINGS_CACHE_TTL_MS = 7 * DAY_MS;
export const ETF_HOLDINGS_REFRESH_COOLDOWN_MS = 30 * SECOND_MS;
export const FUNDAMENTALS_CACHE_TTL_MS = 7 * DAY_MS;
export const FUNDAMENTALS_REFRESH_COOLDOWN_MS = 30 * SECOND_MS;
